version: '3.4'
services:
  samba:
    image: lukics/samba-docker:armv7
    container_name: samba
    environment:
      TZ: 'CST6CDT'
    networks:
      - default
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /datavol/samba:/etc/samba:ro
      - /var/lib/samba:/var/lib/samba
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /datavol:/datavol
      # - /share2:/share2:ro  

networks:
  default:
